{"name": "test_4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'good' in 'hello world'", "trace": "@allure.feature('模块二')\n    @allure.story('这厮一个很niu的测试用例')\n    def test_4():\n        \"\"\"\n        这是对函数的参数，返回值的一个注释\n    \n        \"\"\"\n>       assert \"good\" in \"hello world\"\nE       AssertionError: assert 'good' in 'hello world'\n\ntest_allure.py:31: AssertionError"}, "description": "\n    这是对函数的参数，返回值的一个注释\n\n    ", "start": 1566179278781, "stop": 1566179278781, "uuid": "f082abaf-34c4-4a88-b2c5-2f8346f6770c", "historyId": "a069be209cd5870321eb818addbaf83c", "fullName": "test_allure#test_4", "labels": [{"name": "story", "value": "这厮一个很niu的测试用例"}, {"name": "feature", "value": "模块二"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite"}, {"name": "host", "value": "Caizhanyang"}, {"name": "thread", "value": "6792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}