{"uuid": "cf19f3ed-d5de-4749-8dab-c764c2f4dbb6", "children": ["50206b8c-82a1-4f6e-9760-e972cf3f41ba", "272e6b4f-853e-433e-bb59-805f1d5a3238"], "befores": [{"name": "dr", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command ''D:\\\\Program Files (x86)\\\\Android\\\\android-sdk\\\\platform-tools\\\\adb.exe' -P 5037 -s 5019682f shell getprop ro.build.version.release' exited with code 1'; Stderr: 'error: device unauthorized.\r\nThis adb server's $ADB_VENDOR_KEYS is not set\r\nTry 'adb kill-server' if that seems wrong.\r\nOtherwise check for a confirmation dialog on your device.'; Code: '1'\n\n", "trace": "  File \"d:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 783, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\Darcy\\Desktop\\QQ\\AndroidQQ\\src\\T2\\conftest.py\", line 26, in dr\n    dr_ta = webdriver.Remote('http://localhost:4723/wd/hub', desired_capabilities=ta_phone)\n  File \"d:\\python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 144, in __init__\n    proxy\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1566177619984, "stop": 1566177622125}], "start": 1566177619984, "stop": 1566177622367}